import Testing

@testable import day_08

@Suite
struct Tests {
  let input = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """

  @Test("Puzzle part 1")
  func part1() {
    let puzzle = Puzzle(input: input)
    #expect(puzzle.part1() == 14)
  }

  @Test("Puzzle part 2")
  func part2() {
    let puzzle = Puzzle(input: input)
    #expect(puzzle.part2() == 34)
  }
}
